import { BigTVCategory, QuestionItem } from './types';

// --- Raw Data ---

const BIG_TV_RAW = [
  {
    "id": "movies",
    "nameZh": "電影",
    "nameEn": "Movies",
    "label": "動作",
    "items": [
      {"id": "m1", "zh": "復仇者聯盟", "en": "Avengers"},
      {"id": "m2", "zh": "鐵達尼號", "en": "Titanic"},
      {"id": "m3", "zh": "哈利波特", "en": "Harry Potter"},
      {"id": "m4", "zh": "變形金剛", "en": "Transformers"},
      {"id": "m5", "zh": "侏羅紀公園", "en": "Jurassic Park"},
      {"id": "m6", "zh": "星球大戰", "en": "Star Wars"},
      {"id": "m7", "zh": "魔戒", "en": "Lord of the Rings"},
      {"id": "m8", "zh": "冰雪奇緣", "en": "Frozen"},
      {"id": "m9", "zh": "玩具總動員", "en": "Toy Story"},
      {"id": "m10", "zh": "海底總動員", "en": "Finding Nemo"},
      {"id": "m11", "zh": "蝙蝠俠", "en": "Batman"},
      {"id": "m12", "zh": "阿凡達", "en": "Avatar"},
      {"id": "m13", "zh": "小丑", "en": "Joker"},
      {"id": "m14", "zh": "功夫熊貓", "en": "Kung Fu Panda"},
      {"id": "m15", "zh": "名偵探柯南", "en": "Detective Conan"},
      {"id": "m16", "zh": "怪獸公司", "en": "Monsters Inc"},
      {"id": "m17", "zh": "你的名字", "en": "Your Name"},
      {"id": "m18", "zh": "美女與野獸", "en": "Beauty and the Beast"},
      {"id": "m19", "zh": "小美人魚", "en": "The Little Mermaid"},
      {"id": "m20", "zh": "速度與激情", "en": "Fast and Furious"},
      {"id": "m21", "zh": "鋼鐵俠", "en": "Iron Man"},
      {"id": "m22", "zh": "蜘蛛俠", "en": "Spider-Man"},
      {"id": "m23", "zh": "超人", "en": "Superman"},
      {"id": "m24", "zh": "雷神", "en": "Thor"},
      {"id": "m25", "zh": "黑寡婦", "en": "Black Widow"},
      {"id": "m26", "zh": "奇異博士", "en": "Doctor Strange"},
      {"id": "m27", "zh": "蟻人", "en": "Ant-Man"},
      {"id": "m28", "zh": "銀河護衛隊", "en": "Guardians of the Galaxy"},
      {"id": "m29", "zh": "黑豹", "en": "Black Panther"},
      {"id": "m30", "zh": "驚奇隊長", "en": "Captain Marvel"},
      {"id": "m31", "zh": "獅子王", "en": "The Lion King"},
      {"id": "m32", "zh": "阿拉丁", "en": "Aladdin"},
      {"id": "m33", "zh": "花木蘭", "en": "Mulan"},
      {"id": "m34", "zh": "風中奇緣", "en": "Pocahontas"},
      {"id": "m35", "zh": "灰姑娘", "en": "Cinderella"},
      {"id": "m36", "zh": "睡美人", "en": "Sleeping Beauty"},
      {"id": "m37", "zh": "白雪公主", "en": "Snow White"},
      {"id": "m38", "zh": "小飛象", "en": "Dumbo"},
      {"id": "m39", "zh": "小飛俠", "en": "Peter Pan"},
      {"id": "m40", "zh": "101斑點狗", "en": "101 Dalmatians"},
      {"id": "m41", "zh": "怪獸大學", "en": "Monsters University"},
      {"id": "m42", "zh": "頭腦特工隊", "en": "Inside Out"},
      {"id": "m43", "zh": "尋夢環遊記", "en": "Coco"},
      {"id": "m44", "zh": "超人總動員", "en": "The Incredibles"},
      {"id": "m45", "zh": "料理鼠王", "en": "Ratatouille"},
      {"id": "m46", "zh": "瓦力", "en": "WALL-E"},
      {"id": "m47", "zh": "飛屋環遊記", "en": "Up"},
      {"id": "m48", "zh": "汽車總動員", "en": "Cars"},
      {"id": "m49", "zh": "海底總動員2", "en": "Finding Dory"},
      {"id": "m50", "zh": "瘋狂動物城", "en": "Zootopia"},
      {"id": "m51", "zh": "無敵破壞王", "en": "Wreck-It Ralph"},
      {"id": "m52", "zh": "冰雪奇緣2", "en": "Frozen 2"},
      {"id": "m53", "zh": "魔髮奇緣", "en": "Tangled"},
      {"id": "m54", "zh": "勇敢傳說", "en": "Brave"},
      {"id": "m55", "zh": "馴龍高手", "en": "How to Train Your Dragon"},
      {"id": "m56", "zh": "神偷奶爸", "en": "Despicable Me"},
      {"id": "m57", "zh": "小黃人", "en": "Minions"},
      {"id": "m60", "zh": "瘋狂原始人", "en": "The Croods"},
      {"id": "m62", "zh": "馬達加斯加", "en": "Madagascar"},
      {"id": "m63", "zh": "怪物史萊克", "en": "Shrek"},
      {"id": "m64", "zh": "冰河世紀", "en": "Ice Age"},
      {"id": "m65", "zh": "加勒比海盜", "en": "Pirates of the Caribbean"},
      {"id": "m68", "zh": "終結者", "en": "Terminator"},
      {"id": "m69", "zh": "異形", "en": "Alien"},
      {"id": "m70", "zh": "鐵血戰士", "en": "Predator"},
      {"id": "m71", "zh": "環太平洋", "en": "Pacific Rim"},
      {"id": "m72", "zh": "哥斯拉", "en": "Godzilla"},
      {"id": "m73", "zh": "金剛", "en": "King Kong"},
      {"id": "m74", "zh": "侏羅紀世界", "en": "Jurassic World"},
      {"id": "m78", "zh": "007", "en": "James Bond"},
      {"id": "m79", "zh": "碟中諜", "en": "Mission Impossible"},
      {"id": "m80", "zh": "諜影重重", "en": "The Bourne Identity"}
    ]
  },
  {
    "id": "hk_songs",
    "nameZh": "廣東話歌",
    "nameEn": "Cantonese Songs",
    "label": "動作",
    "items": [
      {"id": "hks1", "zh": "記憶棉", "en": "Memory Foam"},
      {"id": "hks2", "zh": "趁你旅行時搬走", "en": "Move While You Travel"},
      {"id": "hks3", "zh": "緊急聯絡人", "en": "Emergency Contact"},
      {"id": "hks4", "zh": "背脊唱情歌", "en": "Sing Love Songs Behind"},
      {"id": "hks5", "zh": "天梯", "en": "Ladder to Heaven"},
      {"id": "hks6", "zh": "富士山下", "en": "Under Mount Fuji"},
      {"id": "hks7", "zh": "下雨天", "en": "Rainy Day"},
      {"id": "hks8", "zh": "高山低谷", "en": "High Mountains Low Valleys"},
      {"id": "hks9", "zh": "喜帖街", "en": "Wedding Invitation Street"},
      {"id": "hks10", "zh": "野孩子", "en": "Wild Child"},
      {"id": "hks12", "zh": "無人之境", "en": "No Man's Land"},
      {"id": "hks13", "zh": "尋晚", "en": "Last Night"},
      {"id": "hks14", "zh": "座右銘", "en": "Motto"},
      {"id": "hks17", "zh": "心淡", "en": "Heart Faded"},
      {"id": "hks18", "zh": "歡樂今宵", "en": "Happy Tonight"},
      {"id": "hks19", "zh": "一人之境", "en": "One Person's World"},
      {"id": "hks20", "zh": "到此為止", "en": "Stop Here"},
      {"id": "hks21", "zh": "風繼續吹", "en": "Wind Keeps Blowing"},
      {"id": "hks22", "zh": "黑夜不再來", "en": "Dark Night No More"},
      {"id": "hks23", "zh": "愛情轉移", "en": "Love Transfer"},
      {"id": "hks25", "zh": "十年", "en": "Ten Years"},
      {"id": "hks27", "zh": "白玫瑰", "en": "White Rose"},
      {"id": "hks31", "zh": "念念不忘", "en": "Never Forget"},
      {"id": "hks32", "zh": "羅生門", "en": "Rashomon"},
      {"id": "hks33", "zh": "四月物語", "en": "April Story"},
      {"id": "hks34", "zh": "分手總要在雨天", "en": "Breaking Up in the Rain"},
      {"id": "hks35", "zh": "你瞞我瞞", "en": "You Hide I Hide"},
      {"id": "hks36", "zh": "當這地球沒有花", "en": "When This Earth Has No Flowers"},
      {"id": "hks37", "zh": "K歌之王", "en": "King of Karaoke"},
      {"id": "hks38", "zh": "愛得太遲", "en": "Love Too Late"}
    ]
  },
  {
    "id": "tw_songs",
    "nameZh": "國語歌曲",
    "nameEn": "Mandarin Songs",
    "label": "描述",
    "items": [
      {"id": "tws1", "zh": "雨愛", "en": "Rain Love"},
      {"id": "tws2", "zh": "彩虹", "en": "Rainbow"},
      {"id": "tws3", "zh": "龍捲風", "en": "Tornado"},
      {"id": "tws4", "zh": "雙節棍", "en": "Nunchucks"},
      {"id": "tws5", "zh": "告白氣球", "en": "Confession Balloon"},
      {"id": "tws6", "zh": "稻香", "en": "Rice Fragrance"},
      {"id": "tws7", "zh": "安靜", "en": "Quiet"},
      {"id": "tws8", "zh": "晴天", "en": "Sunny Day"},
      {"id": "tws9", "zh": "說好的幸福呢", "en": "Where's the Promised Happiness"},
      {"id": "tws10", "zh": "漂向北方", "en": "Drift to the North"},
      {"id": "tws11", "zh": "愛在西元前", "en": "Love Before A.D."},
      {"id": "tws12", "zh": "青花瓷", "en": "Blue and White Porcelain"},
      {"id": "tws13", "zh": "不能說的秘密", "en": "Secret That Can't Be Told"},
      {"id": "tws14", "zh": "七里香", "en": "Seven Mile Fragrance"},
      {"id": "tws15", "zh": "我不配", "en": "I Don't Deserve"},
      {"id": "tws16", "zh": "小幸運", "en": "Little Luck"},
      {"id": "tws17", "zh": "可惜沒如果", "en": "If Only"},
      {"id": "tws18", "zh": "給我一首歌的時間", "en": "Give Me a Song's Time"},
      {"id": "tws19", "zh": "說愛你", "en": "Say I Love You"},
      {"id": "tws20", "zh": "愛情三十六計", "en": "36 Strategies of Love"},
      {"id": "tws21", "zh": "遇見", "en": "Encounter"},
      {"id": "tws22", "zh": "我懷念的", "en": "What I Miss"},
      {"id": "tws23", "zh": "手寫的從前", "en": "Handwritten Past"},
      {"id": "tws25", "zh": "簡單愛", "en": "Simple Love"},
      {"id": "tws26", "zh": "聽媽媽的話", "en": "Listen to Mom"},
      {"id": "tws27", "zh": "夜曲", "en": "Nocturne"},
      {"id": "tws28", "zh": "髮如雪", "en": "Hair Like Snow"},
      {"id": "tws29", "zh": "千里之外", "en": "Far Away"},
      {"id": "hks11", "zh": "年少有為", "en": "Young and Successful"},
      {"id": "hks15", "zh": "失落沙洲", "en": "Lost Sandbar"},
      {"id": "tws30", "zh": "菊花台", "en": "Chrysanthemum Terrace"}
    ]
  },
  {
    "id": "couple_activities",
    "nameZh": "情侶活動",
    "nameEn": "Couple Activities",
    "label": "動作",
    "items": [
      {"id": "ca1", "zh": "睇 Netflix", "en": "Watch Netflix"},
      {"id": "ca2", "zh": "足底按摩", "en": "Foot Massage"},
      {"id": "ca3", "zh": "Tufting", "en": "Tufting"},
      {"id": "ca4", "zh": "去睇動物", "en": "Visit Animals"},
      {"id": "ca5", "zh": "整蛋糕", "en": "Make Cake"},
      {"id": "ca6", "zh": "拍拖行山", "en": "Date Hiking"},
      {"id": "ca7", "zh": "去主題樂園", "en": "Go to Theme Park"},
      {"id": "ca8", "zh": "去海邊睇日落", "en": "Watch Sunset at Beach"},
      {"id": "ca9", "zh": "打卡 Café", "en": "Check-in Café"},
      {"id": "ca10", "zh": "拍貼紙相", "en": "Take Sticker Photos"},
      {"id": "ca11", "zh": "買 couple 衫", "en": "Buy Couple Clothes"},
      {"id": "ca12", "zh": "一齊煮飯", "en": "Cook Together"},
      {"id": "ca13", "zh": "吹頭", "en": "Blow Dry Hair"},
      {"id": "ca14", "zh": "收拾房間", "en": "Tidy Room"},
      {"id": "ca15", "zh": "做運動", "en": "Exercise"},
      {"id": "ca16", "zh": "夾公仔", "en": "Claw Doll"},
      {"id": "ca17", "zh": "睇星星", "en": "Watch Stars"},
      {"id": "ca18", "zh": "吵架", "en": "Argue"},
      {"id": "ca20", "zh": "購物", "en": "Shopping"},
      {"id": "ca21", "zh": "打機", "en": "Play Games"},
      {"id": "ca22", "zh": "講心事", "en": "Share Feelings"},
      {"id": "ca23", "zh": "食宵夜", "en": "Eat Late Night Snack"},
      {"id": "ca24", "zh": "飯後散步", "en": "Post-meal Walk"}
    ]
  },
  {
    "id": "christmas_gifts",
    "nameZh": "聖誕禮物",
    "nameEn": "Christmas Gifts",
    "label": "描述",
    "items": [
      {"id": "cg1", "zh": "五指襪", "en": "Five-Toe Socks"},
      {"id": "cg2", "zh": "假髮", "en": "Wig"},
      {"id": "cg4", "zh": "香薰蠟燭", "en": "Scented Candle"},
      {"id": "cg5", "zh": "圍巾", "en": "Scarf"},
      {"id": "cg6", "zh": "毛毛拖鞋", "en": "Fuzzy Slippers"},
      {"id": "cg7", "zh": "黑人牙膏", "en": "Black Person Toothpaste"},
      {"id": "cg8", "zh": "一次性底褲", "en": "Disposable Underwear"},
      {"id": "cg9", "zh": "防臭襪", "en": "Anti-Odor Socks"},
      {"id": "cg10", "zh": "電動牙刷", "en": "Electric Toothbrush"},
      {"id": "cg11", "zh": "除毛器", "en": "Hair Remover"},
      {"id": "cg12", "zh": "鼻毛修剪器", "en": "Nose Hair Trimmer"},
      {"id": "cg13", "zh": "腳皮銼", "en": "Foot File"},
      {"id": "cg14", "zh": "去角質磨砂膏", "en": "Exfoliating Scrub"},
      {"id": "cg15", "zh": "止汗劑", "en": "Deodorant"},
      {"id": "cg16", "zh": "漱口水", "en": "Mouthwash"},
      {"id": "cg17", "zh": "牙線", "en": "Dental Floss"},
      {"id": "cg18", "zh": "洗面乳", "en": "Facial Cleanser"},
      {"id": "cg19", "zh": "護手霜", "en": "Hand Cream"},
      {"id": "cg20", "zh": "潤唇膏", "en": "Lip Balm"},
      {"id": "cg21", "zh": "髮蠟", "en": "Hair Wax"},
      {"id": "cg22", "zh": "髮夾", "en": "Hair Clips"},
      {"id": "cg23", "zh": "髮圈", "en": "Hair Ties"},
      {"id": "cg24", "zh": "指甲鉗", "en": "Nail Clippers"},
      {"id": "cg25", "zh": "挖耳勺", "en": "Ear Pick"},
      {"id": "cg26", "zh": "搓澡巾", "en": "Bath Scrubber"},
      {"id": "cg27", "zh": "馬桶刷", "en": "Toilet Brush"},
      {"id": "cg28", "zh": "垃圾袋", "en": "Garbage Bags"},
      {"id": "cg29", "zh": "保鮮膜", "en": "Plastic Wrap"},
      {"id": "cg30", "zh": "保鮮袋", "en": "Ziploc Bags"},
      {"id": "cg31", "zh": "洗碗海綿", "en": "Dish Sponge"},
      {"id": "cg32", "zh": "抹布", "en": "Cleaning Cloth"},
      {"id": "cg33", "zh": "拖把", "en": "Mop"},
      {"id": "cg34", "zh": "垃圾桶", "en": "Trash Can"},
      {"id": "cg35", "zh": "衣架", "en": "Hangers"},
      {"id": "cg36", "zh": "晾衣夾", "en": "Clothespins"},
      {"id": "cg37", "zh": "鞋墊", "en": "Shoe Insoles"},
      {"id": "cg38", "zh": "鞋帶", "en": "Shoelaces"},
      {"id": "cg39", "zh": "襪子", "en": "Socks"},
      {"id": "cg40", "zh": "內衣", "en": "Underwear"},
      {"id": "cg41", "zh": "睡衣", "en": "Pajamas"},
      {"id": "cg42", "zh": "拖鞋", "en": "Slippers"},
      {"id": "cg43", "zh": "眼罩", "en": "Sleep Mask"},
      {"id": "cg44", "zh": "耳塞", "en": "Earplugs"},
      {"id": "cg45", "zh": "鬧鐘", "en": "Alarm Clock"},
      {"id": "cg46", "zh": "手機殼", "en": "Phone Case"},
      {"id": "cg47", "zh": "充電線", "en": "Charging Cable"},
      {"id": "cg48", "zh": "充電器", "en": "Charger"},
      {"id": "cg49", "zh": "手機支架", "en": "Phone Stand"},
      {"id": "cg50", "zh": "鍵盤清潔泥", "en": "Keyboard Cleaning Slime"},
      {"id": "cg51", "zh": "滑鼠墊", "en": "Mouse Pad"},
      {"id": "cg52", "zh": "USB 隨身碟", "en": "USB Flash Drive"},
      {"id": "cg53", "zh": "電池", "en": "Batteries"},
      {"id": "cg54", "zh": "膠帶", "en": "Tape"},
      {"id": "cg55", "zh": "釘書機", "en": "Stapler"},
      {"id": "cg56", "zh": "便利貼", "en": "Sticky Notes"},
      {"id": "cg57", "zh": "筆", "en": "Pen"},
      {"id": "cg58", "zh": "筆記本", "en": "Notebook"},
      {"id": "cg59", "zh": "橡皮擦", "en": "Eraser"},
      {"id": "cg60", "zh": "尺子", "en": "Ruler"},
      {"id": "cg61", "zh": "計算機", "en": "Calculator"},
      {"id": "cg62", "zh": "日曆", "en": "Calendar"},
      {"id": "cg64", "zh": "溫度計", "en": "Thermometer"},
      {"id": "cg65", "zh": "體重計", "en": "Scale"},
      {"id": "cg66", "zh": "雨傘", "en": "Umbrella"},
      {"id": "cg67", "zh": "雨衣", "en": "Raincoat"},
      {"id": "cg68", "zh": "手套", "en": "Gloves"},
      {"id": "cg69", "zh": "帽子", "en": "Hat"},
      {"id": "cg70", "zh": "口罩", "en": "Face Mask"},
      {"id": "cg71", "zh": "濕紙巾", "en": "Wet Wipes"},
      {"id": "cg72", "zh": "衛生紙", "en": "Toilet Paper"},
      {"id": "cg73", "zh": "紙巾", "en": "Tissues"},
      {"id": "cg74", "zh": "棉花棒", "en": "Cotton Swabs"},
      {"id": "cg75", "zh": "創可貼", "en": "Band-Aids"},
      {"id": "cg76", "zh": "藥膏", "en": "Ointment"},
      {"id": "cg77", "zh": "維他命", "en": "Vitamins"},
      {"id": "cg78", "zh": "保健食品", "en": "Health Supplements"},
      {"id": "cg79", "zh": "茶包", "en": "Tea Bags"},
      {"id": "cg80", "zh": "咖啡", "en": "Coffee"},
      {"id": "cg81", "zh": "餅乾", "en": "Cookies"},
      {"id": "cg82", "zh": "糖果", "en": "Candy"},
      {"id": "cg83", "zh": "巧克力", "en": "Chocolate"},
      {"id": "cg84", "zh": "泡麵", "en": "Instant Noodles"},
      {"id": "cg85", "zh": "罐頭", "en": "Canned Food"},
      {"id": "cg86", "zh": "米", "en": "Rice"},
      {"id": "cg87", "zh": "油", "en": "Cooking Oil"},
      {"id": "cg88", "zh": "鹽", "en": "Salt"},
      {"id": "cg89", "zh": "糖", "en": "Sugar"},
      {"id": "cg90", "zh": "醬油", "en": "Soy Sauce"},
      {"id": "cg91", "zh": "醋", "en": "Vinegar"},
      {"id": "cg92", "zh": "胡椒", "en": "Pepper"},
      {"id": "cg93", "zh": "蒜頭", "en": "Garlic"},
      {"id": "cg94", "zh": "洋蔥", "en": "Onion"},
      {"id": "cg95", "zh": "馬鈴薯", "en": "Potato"},
      {"id": "cg96", "zh": "紅蘿蔔", "en": "Carrot"},
      {"id": "cg97", "zh": "雞蛋", "en": "Eggs"},
      {"id": "cg98", "zh": "牛奶", "en": "Milk"},
      {"id": "cg99", "zh": "麵包", "en": "Bread"},
      {"id": "cg100", "zh": "水", "en": "Water"}
    ]
  },
  {
    "id": "animal_idioms",
    "nameZh": "動物成語",
    "nameEn": "Animal Idioms",
    "label": "描述",
    "items": [
      {"id": "ai1", "zh": "鳩佔鵲巢", "en": "Dove Occupies Magpie's Nest"},
      {"id": "ai2", "zh": "九牛二虎", "en": "Nine Oxen Two Tigers"},
      {"id": "ai3", "zh": "打草驚蛇", "en": "Beat Grass to Scare Snake"},
      {"id": "ai4", "zh": "狼心狗肺", "en": "Wolf Heart Dog Lungs"},
      {"id": "ai5", "zh": "虎頭蛇尾", "en": "Tiger Head Snake Tail"},
      {"id": "ai6", "zh": "狐假虎威", "en": "Fox Borrows Tiger's Power"},
      {"id": "ai7", "zh": "魚目混珠", "en": "Mix Fish Eyes with Pearls"},
      {"id": "ai8", "zh": "龍飛鳳舞", "en": "Dragon Flies Phoenix Dances"},
      {"id": "ai9", "zh": "雞手鴨腳", "en": "Chicken Hands Duck Feet"},
      {"id": "ai10", "zh": "龍馬精神", "en": "Dragon Horse Spirit"},
      {"id": "ai11", "zh": "亡羊補牢", "en": "Mend Fence After Sheep Lost"},
      {"id": "ai12", "zh": "馬到成功", "en": "Success Upon Arrival"},
      {"id": "ai13", "zh": "笨鳥先飛", "en": "Clumsy Bird Flies First"},
      {"id": "ai14", "zh": "拔苗助長", "en": "Pull Seedlings to Help Grow"},
      {"id": "ai15", "zh": "虎視眈眈", "en": "Tiger Stares Greedily"},
      {"id": "ai16", "zh": "鸚鵡學舌", "en": "Parrot Learns to Talk"},
      {"id": "ai17", "zh": "狼吞虎嚥", "en": "Wolf Swallows Tiger Devours"},
      {"id": "ai18", "zh": "魚躍龍門", "en": "Fish Leaps Dragon Gate"},
      {"id": "ai19", "zh": "一箭雙鵰", "en": "One Arrow Two Eagles"},
      {"id": "ai20", "zh": "杯弓蛇影", "en": "Cup Bow Snake Shadow"},
      {"id": "ai21", "zh": "守株待兔", "en": "Wait by Tree Stump for Rabbit"},
      {"id": "ai22", "zh": "兔死狐悲", "en": "Fox Grieves Rabbit's Death"},
      {"id": "ai23", "zh": "蠅頭小利", "en": "Fly Head Small Profit"}
    ]
  }
];

const BOMB_QUESTIONS_RAW = [
  "講三個前一個人嘅優點",
  "講三個前一個人嘅缺點",
  "講三個你嘅興趣",
  "三個被炒魷魚嘅原因",
  "三個最想做嘅工作",
  "三個最想買嘅嘢",
  "三個最想學嘅技能",
  "三個最想旅行嘅地方",
  "三個現場嘅人名",
  "三個不能吵鬧嘅地方",
  "用三種語言講我愛你",
  "講出前一個人最像邊種動物？",
  "講一個前一個人一定不知道嘅冷知識",
  "用三個字形容前一個人今日嘅穿搭",
  "形容前一個人嘅戀愛 style",
  "講前一個人如果做 YouTuber，佢會拍咩內容？",
  "講出你覺得前一個人最唔會做嘅工作",
  "前一個人最似邊個卡通人物？",
  "講前一個人最可能上新聞嘅原因",
  "講前一個人如果今日遲到，原因會係咩？",
  "講三個危險職業",
  "講三種不適合帶去太空嘅物品",
  "講三樣你開心時會食嘅嘢",
  "講三個最麻煩嘅家務",
  "講三樣你唔願意 share 嘅私人物品",
  "講三樣如果突然出現在你屋企會嚇到你嘅物體",
  "講三個你絕對講唔出嘅英文單字",
  "講三個你唔識但聽起來好高級嘅職位名",
  "講三個你覺得外星人會帶嚟地球嘅物品",
  "講三樣你覺得廁所最唔應該有嘅嘢",
  "講三個你想一夜之間學識嘅技能",
  "講三個如果你變得超有錢，你會即刻買嘅嘢",
  "講三樣如果你係小朋友，你會偷偷做嘅行為"
];

const WORD_CHAIN_RAW: Record<string, string[]> = {
  "food": [
    "辣嘅食物",
    "甜嘅食物",
    "酸嘅食物",
    "凍嘅食物",
    "熱嘅食物",
    "脆嘅食物",
    "軟嘅食物",
    "健康嘅食物",
    "不健康嘅食物",
    "零食",
    "飲品"
  ],
  "place": [
    "你去過嘅地方",
    "連鎖餐廳",
    "寒冷地方",
    "熱帶地方"
  ],
  "object": [
    "紅色嘅物件",
    "圓形嘅物件",
    "會發光嘅物件",
    "電子產品",
    "魚嘅品種",
    "動物",
    "交通工具",
    "家具",
    "文具"
  ],
  "movie": [
    "動作片",
    "恐怖片",
    "愛情片",
    "動畫片",
    "科幻片",
    "喜劇片",
    "懸疑片",
    "紀錄片"
  ]
};

const FORBIDDEN_RAW = [
  "笑",
  "拍手",
  "摸臉",
  "點頭",
  "搖頭",
  "舉手",
  "站起來",
  "轉身",
  "摸頭髮",
  "摸耳朵",
  "摸鼻子",
  "摸嘴巴",
  "交叉雙手",
  "舉起雙手",
  "閉上眼睛",
  "張開嘴巴",
  "伸出舌頭",
  "揮手",
  "比讚",
  "比YA",
  "摸肚子",
  "摸腳",
  "摸肩膀",
  "摸膝蓋",
  "摸頭",
  "摸脖子",
  "摸手腕",
  "摸手指",
  "摸其他人的手",
  "摸其他人的肩膀",
  "說【你】",
  "說【我】",
  "說【其他人壞話】",
  "說【其他人優點】",
  "說【髒話】"
];

// --- Exported Data ---

export const BIG_TV_CATEGORIES: BigTVCategory[] = BIG_TV_RAW.map(cat => ({
  id: cat.id,
  nameZh: cat.nameZh,
  nameEn: cat.nameEn,
  label: cat.label,
  items: cat.items.map(item => ({ id: item.id, text: item.zh, en: item.en }))
}));

export const BOMB_QUESTIONS: QuestionItem[] = BOMB_QUESTIONS_RAW.map((text, i) => ({
  id: `bq_${i}`,
  text
}));

export const WORD_CHAIN_TOPICS = Object.entries(WORD_CHAIN_RAW).map(([key, items]) => {
  let name = key;
  if (key === 'food') name = '食物';
  else if (key === 'place') name = '地方';
  else if (key === 'object') name = '物件';
  else if (key === 'movie') name = '電影/動畫';

  return {
    id: key,
    name,
    items: items.map((text, i) => ({ id: `wc_${key}_${i}`, text }))
  };
});

export const FORBIDDEN_ACTIONS: QuestionItem[] = FORBIDDEN_RAW.map((text, i) => ({
  id: `fa_${i}`,
  text
}));

export const STORAGE_KEY = 'partybox_question_banks_v1';
